import { Album, User, Review, Activity } from '../types';

// Mock album data with comprehensive track listings
export const mockAlbums: Album[] = [
  {
    id: '1',
    title: 'OK Computer',
    artist: 'Radiohead',
    releaseDate: '1997-06-16',
    genre: ['Alternative Rock', 'Art Rock'],
    coverImageUrl: 'https://i.scdn.co/image/ab67616d0000b273c8b444df094279e70d0ed856',
    description: 'Radiohead\'s third studio album, widely considered one of the greatest albums of all time.',
    trackList: [
      { id: '1-1', trackNumber: 1, title: 'Airbag', duration: 287 },
      { id: '1-2', trackNumber: 2, title: 'Paranoid Android', duration: 383 },
      { id: '1-3', trackNumber: 3, title: 'Subterranean Homesick Alien', duration: 267 },
      { id: '1-4', trackNumber: 4, title: 'Exit Music (For a Film)', duration: 265 },
      { id: '1-5', trackNumber: 5, title: 'Let Down', duration: 299 },
      { id: '1-6', trackNumber: 6, title: 'Karma Police', duration: 261 },
      { id: '1-7', trackNumber: 7, title: 'Fitter Happier', duration: 117 },
      { id: '1-8', trackNumber: 8, title: 'Electioneering', duration: 230 },
      { id: '1-9', trackNumber: 9, title: 'Climbing Up the Walls', duration: 285 },
      { id: '1-10', trackNumber: 10, title: 'No Surprises', duration: 228 },
      { id: '1-11', trackNumber: 11, title: 'Lucky', duration: 259 },
      { id: '1-12', trackNumber: 12, title: 'The Tourist', duration: 324 },
    ],
    externalIds: {
      spotify: '6dVIqQ8qmQ5GBnJ9shOYGE',
    },
  },
  {
    id: '2',
    title: 'In Rainbows',
    artist: 'Radiohead',
    releaseDate: '2007-10-10',
    genre: ['Alternative Rock', 'Art Rock'],
    coverImageUrl: 'https://i.scdn.co/image/ab67616d0000b273f455f624fbc6316c7fb3c9b1',
    description: 'Radiohead\'s seventh studio album, praised for its innovative release strategy and musical content.',
    trackList: [
      { id: '2-1', trackNumber: 1, title: '15 Step', duration: 238 },
      { id: '2-2', trackNumber: 2, title: 'Bodysnatchers', duration: 242 },
      { id: '2-3', trackNumber: 3, title: 'Nude', duration: 261 },
      { id: '2-4', trackNumber: 4, title: 'Weird Fishes/Arpeggi', duration: 318 },
      { id: '2-5', trackNumber: 5, title: 'All I Need', duration: 228 },
      { id: '2-6', trackNumber: 6, title: 'Faust Arp', duration: 130 },
      { id: '2-7', trackNumber: 7, title: 'Reckoner', duration: 290 },
      { id: '2-8', trackNumber: 8, title: 'House of Cards', duration: 339 },
      { id: '2-9', trackNumber: 9, title: 'Jigsaw Falling into Place', duration: 249 },
      { id: '2-10', trackNumber: 10, title: 'Videotape', duration: 287 },
    ],
    externalIds: {
      spotify: '7eyQXxuf2nGj9d2367Gi5f',
    },
  },
  {
    id: '3',
    title: 'To Pimp a Butterfly',
    artist: 'Kendrick Lamar',
    releaseDate: '2015-03-15',
    genre: ['Hip Hop', 'Jazz Rap', 'Conscious Hip Hop'],
    coverImageUrl: 'https://i.scdn.co/image/ab67616d0000b2736ca5c90113b30c3c43ffb8f4',
    description: 'Kendrick Lamar\'s third studio album, exploring themes of racial inequality, depression, and self-love.',
    trackList: [
      { id: '3-1', trackNumber: 1, title: 'Wesley\'s Theory', duration: 287, artist: 'feat. George Clinton & Thundercat' },
      { id: '3-2', trackNumber: 2, title: 'For Free? (Interlude)', duration: 131 },
      { id: '3-3', trackNumber: 3, title: 'King Kunta', duration: 234 },
      { id: '3-4', trackNumber: 4, title: 'Institutionalized', duration: 271, artist: 'feat. Bilal, Anna Wise & Snoop Dogg' },
      { id: '3-5', trackNumber: 5, title: 'These Walls', duration: 300, artist: 'feat. Bilal, Anna Wise & Thundercat' },
      { id: '3-6', trackNumber: 6, title: 'u', duration: 268 },
      { id: '3-7', trackNumber: 7, title: 'Alright', duration: 219 },
      { id: '3-8', trackNumber: 8, title: 'For Sale? (Interlude)', duration: 92 },
      { id: '3-9', trackNumber: 9, title: 'Momma', duration: 283 },
      { id: '3-10', trackNumber: 10, title: 'Hood Politics', duration: 292 },
      { id: '3-11', trackNumber: 11, title: 'How Much a Dollar Cost', duration: 261, artist: 'feat. James Blake & Ronald Isley' },
      { id: '3-12', trackNumber: 12, title: 'Complexion (A Zulu Love)', duration: 264, artist: 'feat. Rapsody' },
      { id: '3-13', trackNumber: 13, title: 'The Blacker the Berry', duration: 328 },
      { id: '3-14', trackNumber: 14, title: 'You Ain\'t Gotta Lie (Momma Said)', duration: 241 },
      { id: '3-15', trackNumber: 15, title: 'i', duration: 341 },
      { id: '3-16', trackNumber: 16, title: 'Mortal Man', duration: 720 },
    ],
    externalIds: {
      spotify: '7ycBtnsMtyVbbwTfJwRjSP',
    },
  },
  {
    id: '4',
    title: 'Blonde',
    artist: 'Frank Ocean',
    releaseDate: '2016-08-20',
    genre: ['R&B', 'Alternative R&B', 'Pop'],
    coverImageUrl: 'https://i.scdn.co/image/ab67616d0000b273c5649add07ed3720be9d5526',
    description: 'Frank Ocean\'s second studio album, a deeply personal and experimental work.',
    trackList: [
      { id: '4-1', trackNumber: 1, title: 'Nikes', duration: 314 },
      { id: '4-2', trackNumber: 2, title: 'Ivy', duration: 249 },
      { id: '4-3', trackNumber: 3, title: 'Pink + White', duration: 184 },
      { id: '4-4', trackNumber: 4, title: 'Be Yourself', duration: 71 },
      { id: '4-5', trackNumber: 5, title: 'Solo', duration: 257 },
      { id: '4-6', trackNumber: 6, title: 'Skyline To', duration: 198 },
      { id: '4-7', trackNumber: 7, title: 'Self Control', duration: 249 },
      { id: '4-8', trackNumber: 8, title: 'Good Guy', duration: 67 },
      { id: '4-9', trackNumber: 9, title: 'Nights', duration: 307 },
      { id: '4-10', trackNumber: 10, title: 'Solo (Reprise)', duration: 93, artist: 'feat. André 3000' },
      { id: '4-11', trackNumber: 11, title: 'Pretty Sweet', duration: 178 },
      { id: '4-12', trackNumber: 12, title: 'Facebook Story', duration: 80 },
      { id: '4-13', trackNumber: 13, title: 'Close to You', duration: 90 },
      { id: '4-14', trackNumber: 14, title: 'White Ferrari', duration: 250 },
      { id: '4-15', trackNumber: 15, title: 'Seigfried', duration: 345 },
      { id: '4-16', trackNumber: 16, title: 'Godspeed (Sweet Dreams)', duration: 198 },
      { id: '4-17', trackNumber: 17, title: 'Futura Free', duration: 549 },
    ],
    externalIds: {
      spotify: '3mH6qwIy9crq0I9YQbOuDf',
    },
  },
  {
    id: '5',
    title: 'Good Kid, M.A.A.D City',
    artist: 'Kendrick Lamar',
    releaseDate: '2012-10-22',
    genre: ['Hip Hop', 'West Coast Hip Hop'],
    coverImageUrl: 'https://i.scdn.co/image/ab67616d0000b273d6dce7b1d9bb3e6f2b6a8b8b',
    description: 'Kendrick Lamar\'s major label debut, a concept album about his experiences growing up in Compton.',
    trackList: [
      { id: '5-1', trackNumber: 1, title: 'Sherane a.k.a Master Splinter\'s Daughter', duration: 279 },
      { id: '5-2', trackNumber: 2, title: 'Bitch, Don\'t Kill My Vibe', duration: 320 },
      { id: '5-3', trackNumber: 3, title: 'Backseat Freestyle', duration: 213 },
      { id: '5-4', trackNumber: 4, title: 'The Art of Peer Pressure', duration: 332 },
      { id: '5-5', trackNumber: 5, title: 'Money Trees', duration: 386, artist: 'feat. Jay Rock' },
      { id: '5-6', trackNumber: 6, title: 'Poetic Justice', duration: 301, artist: 'feat. Drake' },
      { id: '5-7', trackNumber: 7, title: 'good kid', duration: 347 },
      { id: '5-8', trackNumber: 8, title: 'm.A.A.d city', duration: 339, artist: 'feat. MC Eiht' },
      { id: '5-9', trackNumber: 9, title: 'Swimming Pools (Drank)', duration: 312 },
      { id: '5-10', trackNumber: 10, title: 'Sing About Me, I\'m Dying of Thirst', duration: 720 },
      { id: '5-11', trackNumber: 11, title: 'Real', duration: 474, artist: 'feat. Anna Wise' },
      { id: '5-12', trackNumber: 12, title: 'Compton', duration: 248, artist: 'feat. Dr. Dre' },
    ],
    externalIds: {
      spotify: '4eLPsYPBmXABThSJ821sqY',
    },
  },
  {
    id: '6',
    title: 'Dark Side of the Moon',
    artist: 'Pink Floyd',
    releaseDate: '1973-03-01',
    genre: ['Progressive Rock', 'Psychedelic Rock'],
    coverImageUrl: 'https://i.scdn.co/image/ab67616d0000b273ea7caaff71dea1051d49b2fe',
    description: 'Pink Floyd\'s eighth studio album, one of the best-selling albums of all time.',
    trackList: [
      { id: '6-1', trackNumber: 1, title: 'Speak to Me', duration: 90 },
      { id: '6-2', trackNumber: 2, title: 'Breathe (In the Air)', duration: 163 },
      { id: '6-3', trackNumber: 3, title: 'On the Run', duration: 216 },
      { id: '6-4', trackNumber: 4, title: 'Time', duration: 413 },
      { id: '6-5', trackNumber: 5, title: 'The Great Gig in the Sky', duration: 283 },
      { id: '6-6', trackNumber: 6, title: 'Money', duration: 382 },
      { id: '6-7', trackNumber: 7, title: 'Us and Them', duration: 467 },
      { id: '6-8', trackNumber: 8, title: 'Any Colour You Like', duration: 205 },
      { id: '6-9', trackNumber: 9, title: 'Brain Damage', duration: 228 },
      { id: '6-10', trackNumber: 10, title: 'Eclipse', duration: 123 },
    ],
    externalIds: {
      spotify: '4LH4d3cOWNNsVw41Gqt2kv',
    },
  },
  {
    id: '7',
    title: 'Abbey Road',
    artist: 'The Beatles',
    releaseDate: '1969-09-26',
    genre: ['Rock', 'Pop Rock'],
    coverImageUrl: 'https://i.scdn.co/image/ab67616d0000b273dc30583ba717007b00cceb25',
    description: 'The Beatles\' eleventh studio album, featuring iconic songs and production.',
    trackList: [
      { id: '7-1', trackNumber: 1, title: 'Come Together', duration: 259 },
      { id: '7-2', trackNumber: 2, title: 'Something', duration: 183 },
      { id: '7-3', trackNumber: 3, title: 'Maxwell\'s Silver Hammer', duration: 207 },
      { id: '7-4', trackNumber: 4, title: 'Oh! Darling', duration: 206 },
      { id: '7-5', trackNumber: 5, title: 'Octopus\'s Garden', duration: 171 },
      { id: '7-6', trackNumber: 6, title: 'I Want You (She\'s So Heavy)', duration: 467 },
      { id: '7-7', trackNumber: 7, title: 'Here Comes the Sun', duration: 185 },
      { id: '7-8', trackNumber: 8, title: 'Because', duration: 165 },
      { id: '7-9', trackNumber: 9, title: 'You Never Give Me Your Money', duration: 227 },
      { id: '7-10', trackNumber: 10, title: 'Sun King', duration: 186 },
      { id: '7-11', trackNumber: 11, title: 'Mean Mr. Mustard', duration: 66 },
      { id: '7-12', trackNumber: 12, title: 'Polythene Pam', duration: 72 },
      { id: '7-13', trackNumber: 13, title: 'She Came in Through the Bathroom Window', duration: 117 },
      { id: '7-14', trackNumber: 14, title: 'Golden Slumbers', duration: 91 },
      { id: '7-15', trackNumber: 15, title: 'Carry That Weight', duration: 96 },
      { id: '7-16', trackNumber: 16, title: 'The End', duration: 140 },
      { id: '7-17', trackNumber: 17, title: 'Her Majesty', duration: 23 },
    ],
    externalIds: {
      spotify: '0ETFjACtuP2ADo6LFhL6HN',
    },
  },
  {
    id: '8',
    title: 'Nevermind',
    artist: 'Nirvana',
    releaseDate: '1991-09-24',
    genre: ['Grunge', 'Alternative Rock'],
    coverImageUrl: 'https://i.scdn.co/image/ab67616d0000b27326cc1cae1c4493c96a3d2f2b',
    description: 'Nirvana\'s second studio album that brought grunge to mainstream success.',
    trackList: [
      { id: '8-1', trackNumber: 1, title: 'Smells Like Teen Spirit', duration: 301 },
      { id: '8-2', trackNumber: 2, title: 'In Bloom', duration: 254 },
      { id: '8-3', trackNumber: 3, title: 'Come As You Are', duration: 219 },
      { id: '8-4', trackNumber: 4, title: 'Breed', duration: 183 },
      { id: '8-5', trackNumber: 5, title: 'Lithium', duration: 257 },
      { id: '8-6', trackNumber: 6, title: 'Polly', duration: 177 },
      { id: '8-7', trackNumber: 7, title: 'Territorial Pissings', duration: 143 },
      { id: '8-8', trackNumber: 8, title: 'Drain You', duration: 223 },
      { id: '8-9', trackNumber: 9, title: 'Lounge Act', duration: 156 },
      { id: '8-10', trackNumber: 10, title: 'Stay Away', duration: 212 },
      { id: '8-11', trackNumber: 11, title: 'On a Plain', duration: 196 },
      { id: '8-12', trackNumber: 12, title: 'Something in the Way', duration: 231 },
    ],
    externalIds: {
      spotify: '2UJwKSBUz6rtW4QLK74kQu',
    },
  },
  {
    id: '9',
    title: 'The Velvet Underground & Nico',
    artist: 'The Velvet Underground',
    releaseDate: '1967-03-12',
    genre: ['Art Rock', 'Experimental Rock'],
    coverImageUrl: 'https://i.scdn.co/image/ab67616d0000b273512354629c1a9ee3b2b0a3e3',
    description: 'The influential debut album by The Velvet Underground, produced by Andy Warhol.',
    trackList: [
      { id: '9-1', trackNumber: 1, title: 'Sunday Morning', duration: 175 },
      { id: '9-2', trackNumber: 2, title: 'I\'m Waiting for the Man', duration: 266 },
      { id: '9-3', trackNumber: 3, title: 'Femme Fatale', duration: 137 },
      { id: '9-4', trackNumber: 4, title: 'Venus in Furs', duration: 315 },
      { id: '9-5', trackNumber: 5, title: 'Run Run Run', duration: 262 },
      { id: '9-6', trackNumber: 6, title: 'All Tomorrow\'s Parties', duration: 356 },
      { id: '9-7', trackNumber: 7, title: 'Heroin', duration: 427 },
      { id: '9-8', trackNumber: 8, title: 'There She Goes Again', duration: 154 },
      { id: '9-9', trackNumber: 9, title: 'I\'ll Be Your Mirror', duration: 134 },
      { id: '9-10', trackNumber: 10, title: 'The Black Angel\'s Death Song', duration: 189 },
      { id: '9-11', trackNumber: 11, title: 'European Son', duration: 467 },
    ],
    externalIds: {
      spotify: '2lqULKip8L5qbL8Dy2w1sW',
    },
  },
  {
    id: '10',
    title: 'Blue',
    artist: 'Joni Mitchell',
    releaseDate: '1971-06-22',
    genre: ['Folk', 'Singer-Songwriter'],
    coverImageUrl: 'https://i.scdn.co/image/ab67616d0000b273b9ab3605a3bfe9fc8b83cbb7',
    description: 'Joni Mitchell\'s fourth studio album, widely considered one of the greatest albums ever made.',
    trackList: [
      { id: '10-1', trackNumber: 1, title: 'All I Want', duration: 213 },
      { id: '10-2', trackNumber: 2, title: 'My Old Man', duration: 227 },
      { id: '10-3', trackNumber: 3, title: 'Little Green', duration: 212 },
      { id: '10-4', trackNumber: 4, title: 'Carey', duration: 180 },
      { id: '10-5', trackNumber: 5, title: 'Blue', duration: 186 },
      { id: '10-6', trackNumber: 6, title: 'California', duration: 234 },
      { id: '10-7', trackNumber: 7, title: 'This Flight Tonight', duration: 202 },
      { id: '10-8', trackNumber: 8, title: 'River', duration: 240 },
      { id: '10-9', trackNumber: 9, title: 'A Case of You', duration: 260 },
      { id: '10-10', trackNumber: 10, title: 'The Last Time I Saw Richard', duration: 248 },
    ],
    externalIds: {
      spotify: '1vz94WpXDVDFNenSLtVlam',
    },
  },
  {
    id: '11',
    title: 'The Queen Is Dead',
    artist: 'The Smiths',
    releaseDate: '1986-06-16',
    genre: ['Alternative Rock', 'Indie Pop'],
    coverImageUrl: 'https://i.scdn.co/image/ab67616d0000b273208560ea5d2c22b80e8b1c0e',
    description: 'The Smiths\' third studio album, often cited as their masterpiece.',
    trackList: [
      { id: '11-1', trackNumber: 1, title: 'The Queen Is Dead', duration: 375 },
      { id: '11-2', trackNumber: 2, title: 'Frankly, Mr. Shankly', duration: 139 },
      { id: '11-3', trackNumber: 3, title: 'I Know It\'s Over', duration: 348 },
      { id: '11-4', trackNumber: 4, title: 'Never Had No One Ever', duration: 214 },
      { id: '11-5', trackNumber: 5, title: 'Cemetry Gates', duration: 169 },
      { id: '11-6', trackNumber: 6, title: 'Bigmouth Strikes Again', duration: 196 },
      { id: '11-7', trackNumber: 7, title: 'The Boy with the Thorn in His Side', duration: 234 },
      { id: '11-8', trackNumber: 8, title: 'Vicar in a Tutu', duration: 144 },
      { id: '11-9', trackNumber: 9, title: 'There Is a Light That Never Goes Out', duration: 244 },
      { id: '11-10', trackNumber: 10, title: 'Some Girls Are Bigger Than Others', duration: 205 },
    ],
    externalIds: {
      spotify: '1F7DDzTHir2QpBTcJQ8H6x',
    },
  },
  {
    id: '12',
    title: 'Random Access Memories',
    artist: 'Daft Punk',
    releaseDate: '2013-05-17',
    genre: ['Electronic', 'Disco', 'Funk'],
    coverImageUrl: 'https://i.scdn.co/image/ab67616d0000b273da54d1c4dac32b0b7c3e1e8a',
    description: 'Daft Punk\'s fourth studio album, featuring live instrumentation and disco influences.',
    trackList: [
      { id: '12-1', trackNumber: 1, title: 'Give Life Back to Music', duration: 275 },
      { id: '12-2', trackNumber: 2, title: 'The Game of Love', duration: 323 },
      { id: '12-3', trackNumber: 3, title: 'Giorgio by Moroder', duration: 544 },
      { id: '12-4', trackNumber: 4, title: 'Within', duration: 228 },
      { id: '12-5', trackNumber: 5, title: 'Instant Crush', duration: 337 },
      { id: '12-6', trackNumber: 6, title: 'Lose Yourself to Dance', duration: 353 },
      { id: '12-7', trackNumber: 7, title: 'Touch', duration: 498 },
      { id: '12-8', trackNumber: 8, title: 'Get Lucky', duration: 368 },
      { id: '12-9', trackNumber: 9, title: 'Beyond', duration: 290 },
      { id: '12-10', trackNumber: 10, title: 'Motherboard', duration: 343 },
      { id: '12-11', trackNumber: 11, title: 'Fragments of Time', duration: 279 },
      { id: '12-12', trackNumber: 12, title: 'Doin\' It Right', duration: 251 },
      { id: '12-13', trackNumber: 13, title: 'Contact', duration: 381 },
    ],
    externalIds: {
      spotify: '4m2880jivSbbyEGAKfITCa',
    },
  },
  {
    id: '13',
    title: 'Thriller',
    artist: 'Michael Jackson',
    releaseDate: '1982-11-30',
    genre: ['Pop', 'R&B', 'Rock'],
    coverImageUrl: 'https://i.scdn.co/image/ab67616d0000b2734121faee8df82c526cbab2be',
    description: 'Michael Jackson\'s sixth studio album, the best-selling album of all time.',
    trackList: [
      { id: '13-1', trackNumber: 1, title: 'Wanna Be Startin\' Somethin\'', duration: 363 },
      { id: '13-2', trackNumber: 2, title: 'Baby Be Mine', duration: 260 },
      { id: '13-3', trackNumber: 3, title: 'The Girl Is Mine', duration: 222 },
      { id: '13-4', trackNumber: 4, title: 'Thriller', duration: 357 },
      { id: '13-5', trackNumber: 5, title: 'Beat It', duration: 258 },
      { id: '13-6', trackNumber: 6, title: 'Billie Jean', duration: 294 },
      { id: '13-7', trackNumber: 7, title: 'Human Nature', duration: 246 },
      { id: '13-8', trackNumber: 8, title: 'P.Y.T. (Pretty Young Thing)', duration: 239 },
      { id: '13-9', trackNumber: 9, title: 'The Lady in My Life', duration: 300 },
    ],
    externalIds: {
      spotify: '2ANVost0y2y52ema1E9xAZ',
    },
  },
  {
    id: '14',
    title: 'To Pimp a Butterfly',
    artist: 'Kendrick Lamar',
    releaseDate: '2015-03-15',
    genre: ['Hip Hop', 'Jazz Rap', 'Conscious Hip Hop'],
    coverImageUrl: 'https://i.scdn.co/image/ab67616d0000b273cdb645498cd3d8a2abcaedc7',
    description: 'Kendrick Lamar\'s third studio album, acclaimed for its innovative production and social commentary.',
    trackList: [
      { id: '14-1', trackNumber: 1, title: 'Wesley\'s Theory', duration: 287 },
      { id: '14-2', trackNumber: 2, title: 'For Free? (Interlude)', duration: 126 },
      { id: '14-3', trackNumber: 3, title: 'King Kunta', duration: 234 },
      { id: '14-4', trackNumber: 4, title: 'Institutionalized', duration: 271 },
      { id: '14-5', trackNumber: 5, title: 'These Walls', duration: 305 },
      { id: '14-6', trackNumber: 6, title: 'u', duration: 268 },
      { id: '14-7', trackNumber: 7, title: 'Alright', duration: 219 },
      { id: '14-8', trackNumber: 8, title: 'For Sale? (Interlude)', duration: 92 },
      { id: '14-9', trackNumber: 9, title: 'Momma', duration: 283 },
      { id: '14-10', trackNumber: 10, title: 'Hood Politics', duration: 292 },
      { id: '14-11', trackNumber: 11, title: 'How Much a Dollar Cost', duration: 261 },
      { id: '14-12', trackNumber: 12, title: 'Complexion (A Zulu Love)', duration: 261 },
      { id: '14-13', trackNumber: 13, title: 'The Blacker the Berry', duration: 328 },
      { id: '14-14', trackNumber: 14, title: 'You Ain\'t Gotta Lie (Momma Said)', duration: 241 },
      { id: '14-15', trackNumber: 15, title: 'i', duration: 345 },
      { id: '14-16', trackNumber: 16, title: 'Mortal Man', duration: 720 },
    ],
    externalIds: {
      spotify: '7ycBtnsMtyVbbwTfJwRjSP',
    },
  },
  {
    id: '15',
    title: 'Pet Sounds',
    artist: 'The Beach Boys',
    releaseDate: '1966-05-16',
    genre: ['Pop', 'Psychedelic Pop', 'Art Pop'],
    coverImageUrl: 'https://i.scdn.co/image/ab67616d0000b273736b2bfc01e768b8bd8d6adf',
    description: 'The Beach Boys\' eleventh studio album, often cited as one of the most influential albums ever made.',
    trackList: [
      { id: '15-1', trackNumber: 1, title: 'Wouldn\'t It Be Nice', duration: 152 },
      { id: '15-2', trackNumber: 2, title: 'You Still Believe in Me', duration: 147 },
      { id: '15-3', trackNumber: 3, title: 'That\'s Not Me', duration: 146 },
      { id: '15-4', trackNumber: 4, title: 'Don\'t Talk (Put Your Head on My Shoulder)', duration: 171 },
      { id: '15-5', trackNumber: 5, title: 'I\'m Waiting for the Day', duration: 195 },
      { id: '15-6', trackNumber: 6, title: 'Let\'s Go Away for Awhile', duration: 134 },
      { id: '15-7', trackNumber: 7, title: 'Sloop John B', duration: 177 },
      { id: '15-8', trackNumber: 8, title: 'God Only Knows', duration: 168 },
      { id: '15-9', trackNumber: 9, title: 'I Know There\'s an Answer', duration: 195 },
      { id: '15-10', trackNumber: 10, title: 'Here Today', duration: 167 },
      { id: '15-11', trackNumber: 11, title: 'I Just Wasn\'t Made for These Times', duration: 192 },
      { id: '15-12', trackNumber: 12, title: 'Pet Sounds', duration: 126 },
      { id: '15-13', trackNumber: 13, title: 'Caroline, No', duration: 170 },
    ],
    externalIds: {
      spotify: '5HbN9GxfRTDLpCyGsy2bS5',
    },
  },
];

// Mock user data
export const mockUsers: User[] = [
  {
    id: 'user1',
    username: 'musiclover2024',
    email: 'music@example.com',
    profilePicture: 'https://randomuser.me/api/portraits/men/32.jpg',
    bio: 'Passionate about discovering new music across all genres',
    joinedDate: new Date('2024-01-15'),
    lastActiveDate: new Date(),
    preferences: {
      favoriteGenres: ['Alternative Rock', 'Hip Hop', 'Jazz'],
      favoriteAlbumIds: ['1', '2'], // Add missing property
      notifications: {
        newFollowers: true,
        reviewLikes: true,
        friendActivity: true,
      },
      privacy: {
        profileVisibility: 'public',
        activityVisibility: 'public',
      },
    },
  },
  {
    id: 'user2',
    username: 'vinylcollector',
    email: 'vinyl@example.com',
    profilePicture: 'https://randomuser.me/api/portraits/women/44.jpg',
    bio: 'Collecting records since 1995 🎶',
    joinedDate: new Date('2023-11-20'),
    lastActiveDate: new Date(Date.now() - 86400000), // Yesterday
    preferences: {
      favoriteGenres: ['Classic Rock', 'Blues', 'Soul'],
      favoriteAlbumIds: [], // Add missing property
      notifications: {
        newFollowers: true,
        reviewLikes: false,
        friendActivity: true,
      },
      privacy: {
        profileVisibility: 'public',
        activityVisibility: 'friends',
      },
    },
  },
];

// Mock reviews
export const mockReviews: Review[] = [
  {
    id: 'review1',
    userId: 'user1',
    albumId: '1',
    rating: 5,
    reviewText: 'A masterpiece that defined a generation. Every track is perfection.',
    dateReviewed: new Date('2024-01-20'),
    likesCount: 24,
    commentsCount: 8,
  },
  {
    id: 'review2',
    userId: 'user2',
    albumId: '3',
    rating: 5,
    reviewText: 'Kendrick\'s most important work. A powerful statement on race and society.',
    dateReviewed: new Date('2024-01-18'),
    likesCount: 31,
    commentsCount: 12,
  },
];

// Mock activity feed
export const mockActivities: Activity[] = [
  {
    id: 'activity1',
    userId: 'user1',
    type: 'review',
    albumId: '1',
    reviewId: 'review1',
    timestamp: new Date('2024-01-20'),
  },
  {
    id: 'activity2',
    userId: 'user2',
    type: 'listen',
    albumId: '4',
    timestamp: new Date('2024-01-19'),
  },
  {
    id: 'activity3',
    userId: 'user1',
    type: 'listen',
    albumId: '2',
    timestamp: new Date('2024-01-18'),
  },
];

// Popular genres for quick search
export const popularGenres = [
  'Rock',
  'Hip Hop',
  'Pop',
  'Electronic',
  'Jazz',
  'Classical',
  'R&B',
  'Country',
  'Folk',
  'Metal',
];